name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: meeploy-server
          path: |
            dist
            package.json
            yarn.lock